/*
 * The MIT License
 *
 * Copyright 2017 Lars.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package gui;


import entity.Customer;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import logic.CustomerService;
import logic.EnumServices;

/**
 *
 * @author Lars
 */
public class newCustomer extends javax.swing.JDialog {

    /**
     * Creates new form newCustomer
     */
    public newCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        parent.setEnabled(false);
        //Set dropdown form DB 
        EnumServices ES = new EnumServices();
        HashMap<Integer, String> companyStage = ES.getCompanyStage();
        String[] toArray = (String[]) companyStage.values().toArray(new String[companyStage.size()]);
        jCBCompanyStage.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));
        
        HashMap<Integer, String> industry = ES.getIndustry();
        toArray = (String[]) industry.values().toArray(new String[industry.size()]);
        jCBIndustry.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));

        HashMap<Integer, String> channel = ES.getChannel();
        toArray = (String[]) channel.values().toArray(new String[channel.size()]);
        jCBChannel.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCustomer = new javax.swing.JLabel();
        jTFCustomerName = new javax.swing.JTextField();
        jLIndustry = new javax.swing.JLabel();
        jCBIndustry = new javax.swing.JComboBox<>();
        jLStage = new javax.swing.JLabel();
        jCBCompanyStage = new javax.swing.JComboBox<>();
        jLChannel = new javax.swing.JLabel();
        jCBChannel = new javax.swing.JComboBox<>();
        jCBInternal = new javax.swing.JCheckBox();
        jBSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jLCustomer.setText("Mandantenname");
        getContentPane().add(jLCustomer);

        jTFCustomerName.setToolTipText("Mandantenname");
        getContentPane().add(jTFCustomerName);

        jLIndustry.setText("Welcher Branche gehört der Mandant an");
        getContentPane().add(jLIndustry);
        getContentPane().add(jCBIndustry);

        jLStage.setText("In welcher Unternehmensphasen befindet sich der Mandant");
        getContentPane().add(jLStage);
        getContentPane().add(jCBCompanyStage);

        jLChannel.setText("Über welchen Kanal wurde das Mandats-Unternehmen gewonnen?");
        getContentPane().add(jLChannel);

        getContentPane().add(jCBChannel);

        jCBInternal.setText("Intern");
        getContentPane().add(jCBInternal);

        jBSave.setText("Speichern");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jBSave);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        String S = jTFCustomerName.getText();
        // public Customer(String customername, int industryNumber, int companyStageNumber, int Channel, boolean internal) {
        int selectedIndexchanel = jCBChannel.getSelectedIndex();
        int selectedIndexCompanyStage = jCBCompanyStage.getSelectedIndex();
        int selectedIndexindustry = jCBIndustry.getSelectedIndex();
        boolean internal = jCBInternal.isSelected();
        Customer c = new Customer(S, selectedIndexindustry, selectedIndexCompanyStage, selectedIndexchanel, internal);
        CustomerService CTS = new CustomerService();
        TreeMap<String, Customer> allCustomers = CTS.getAllCustomers();
        Customer get = allCustomers.get(S);
        int bevor = allCustomers.size();
        if (get == null) {
            allCustomers.put(c.getCustomername(), c);
            int saveCustomer = CTS.saveCustomer(c);
            c.setId(saveCustomer);
        } else {
            JOptionPane.showMessageDialog(null, "Mandant schon vorhanden!");
        }
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSave;
    private javax.swing.JComboBox<String> jCBChannel;
    private javax.swing.JComboBox<String> jCBCompanyStage;
    private javax.swing.JComboBox<String> jCBIndustry;
    private javax.swing.JCheckBox jCBInternal;
    private javax.swing.JLabel jLChannel;
    private javax.swing.JLabel jLCustomer;
    private javax.swing.JLabel jLIndustry;
    private javax.swing.JLabel jLStage;
    private javax.swing.JTextField jTFCustomerName;
    // End of variables declaration//GEN-END:variables
}
