/*
 * The MIT License
 *
 * Copyright 2017 Lars.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package gui;

import entity.Customer;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import logic.CustomerService;
import logic.EnumServices;

/**
 *
 * @author Lars
 */
public class newCustomer extends javax.swing.JDialog {

    /**
     * Creates new form newCustomer
     */
    public newCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        parent.setEnabled(false);
        jBSave.setEnabled(true);
        //Set dropdown form DB 
        EnumServices ES = new EnumServices();
        HashMap<Integer, String> companyStage = ES.getCompanyStage();
        String[] toArray = (String[]) companyStage.values().toArray(new String[companyStage.size()]);
        jCBCompanyStage.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));

        HashMap<Integer, String> industry = ES.getIndustry();
        toArray = (String[]) industry.values().toArray(new String[industry.size()]);
        jCBIndustry.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));

        HashMap<Integer, String> channel = ES.getChannel();
        toArray = (String[]) channel.values().toArray(new String[channel.size()]);
        jCBChannel.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));

    }

    public newCustomer(java.awt.Frame parent, boolean modal, Customer customer) {
        super(parent, modal);
        initComponents();
        parent.setEnabled(false);
        jTFCustomerName.setEnabled(false);
        jBrefresh.setEnabled(true);
        //Set dropdown form DB 
        EnumServices ES = new EnumServices();
        HashMap<Integer, String> companyStage = ES.getCompanyStage();
        String[] toArray = (String[]) companyStage.values().toArray(new String[companyStage.size()]);
        jCBCompanyStage.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));

        jCBCompanyStage.setSelectedIndex(customer.getCompanyStageNumber());

        HashMap<Integer, String> industry = ES.getIndustry();
        toArray = (String[]) industry.values().toArray(new String[industry.size()]);
        jCBIndustry.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));
        jCBIndustry.setSelectedIndex(customer.getIndustryNumber());

        HashMap<Integer, String> channel = ES.getChannel();
        toArray = (String[]) channel.values().toArray(new String[channel.size()]);
        jCBChannel.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));
        jCBChannel.setSelectedIndex(customer.getChannel());

        jTFCustomerName.setText(customer.getCustomername());
        jCBInternal.setSelected(customer.isInternal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCustomer = new javax.swing.JLabel();
        jTFCustomerName = new javax.swing.JTextField();
        jLIndustry = new javax.swing.JLabel();
        jCBIndustry = new javax.swing.JComboBox<>();
        jLStage = new javax.swing.JLabel();
        jCBCompanyStage = new javax.swing.JComboBox<>();
        jLChannel = new javax.swing.JLabel();
        jCBChannel = new javax.swing.JComboBox<>();
        jCBInternal = new javax.swing.JCheckBox();
        jBSave = new javax.swing.JButton();
        jBrefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(475, 330));
        setMinimumSize(new java.awt.Dimension(475, 330));
        setPreferredSize(new java.awt.Dimension(475, 330));

        jLCustomer.setText("Mandantenname");

        jTFCustomerName.setToolTipText("Mandantenname");

        jLIndustry.setText("Welcher Branche gehört der Mandant an");

        jLStage.setText("In welcher Unternehmensphasen befindet sich der Mandant");

        jLChannel.setText("Über welchen Kanal wurde das Mandats-Unternehmen gewonnen?");

        jCBInternal.setText("Intern");

        jBSave.setText("Speichern");
        jBSave.setEnabled(false);
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jBrefresh.setText("Aktualisieren");
        jBrefresh.setAutoscrolls(true);
        jBrefresh.setEnabled(false);
        jBrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFCustomerName)
            .addComponent(jBSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCBInternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCBIndustry, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCBCompanyStage, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCBChannel, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLIndustry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(164, 164, 164))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLStage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addComponent(jLChannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(114, 114, 114))))
            .addComponent(jBrefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jCBIndustry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jCBCompanyStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLIndustry)
                        .addGap(27, 27, 27)
                        .addComponent(jLStage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLChannel)
                .addGap(12, 12, 12)
                .addComponent(jCBChannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jCBInternal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBrefresh))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        String S = jTFCustomerName.getText();
        int selectedIndexchanel = jCBChannel.getSelectedIndex();
        int selectedIndexCompanyStage = jCBCompanyStage.getSelectedIndex();
        int selectedIndexindustry = jCBIndustry.getSelectedIndex();
        boolean internal = jCBInternal.isSelected();
        Customer c = new Customer(S, selectedIndexindustry, selectedIndexCompanyStage, selectedIndexchanel, internal);
        CustomerService CTS = new CustomerService();
        TreeMap<String, Customer> allCustomers = CTS.getAllCustomers();
        Customer get = allCustomers.get(S);
        int bevor = allCustomers.size();
        if (get == null) {
            allCustomers.put(c.getCustomername(), c);
            int saveCustomer = CTS.saveCustomer(c);
            c.setId(saveCustomer);
        } else {
            JOptionPane.showMessageDialog(null, "Mandant schon vorhanden!");
        }
        dispose();
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jBrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrefreshActionPerformed
        String S = jTFCustomerName.getText();
        CustomerService CTS = new CustomerService();
        TreeMap<String, Customer> allCustomers = CTS.getAllCustomers();
        Customer get = allCustomers.get(S);

        int selectedIndexchanel = jCBChannel.getSelectedIndex();
        int selectedIndexCompanyStage = jCBCompanyStage.getSelectedIndex();
        int selectedIndexindustry = jCBIndustry.getSelectedIndex();
        boolean internal = jCBInternal.isSelected();
        // get.setCustomername(S);
        get.setChannel(selectedIndexchanel);
        get.setCompanyStageNumber(selectedIndexCompanyStage);
        get.setIndustryNumber(selectedIndexindustry);
        get.setInternal(internal);

        int saveCustomer = CTS.saveCustomer(get);
        // c.setId(saveCustomer);

        dispose();
    }//GEN-LAST:event_jBrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSave;
    private javax.swing.JButton jBrefresh;
    private javax.swing.JComboBox<String> jCBChannel;
    private javax.swing.JComboBox<String> jCBCompanyStage;
    private javax.swing.JComboBox<String> jCBIndustry;
    private javax.swing.JCheckBox jCBInternal;
    private javax.swing.JLabel jLChannel;
    private javax.swing.JLabel jLCustomer;
    private javax.swing.JLabel jLIndustry;
    private javax.swing.JLabel jLStage;
    private javax.swing.JTextField jTFCustomerName;
    // End of variables declaration//GEN-END:variables
}
