/*
 * The MIT License
 *
 * Copyright 2017 Lars.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package gui;
import entity.*;

import entity.Customer;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import logic.CustomerService;
import logic.EnumServices;

/**
 *
 * @author Lars
 */
public class newCustomer extends javax.swing.JDialog {

    /**
     * Creates new form newCustomer
     */
    public newCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        parent.setEnabled(false);
        //Set dropdown form DB 
        EnumServices ES = new EnumServices();
        HashMap<Integer, String> companyStage = ES.getCompanyStage();
        String[] toArray = (String[]) companyStage.values().toArray(new String[companyStage.size()]);

        Vector model = new Vector();
        for (Map.Entry<Integer, String> entry : companyStage.entrySet()) {
            Integer key = entry.getKey();
            String value = entry.getValue();
            //model.addElement(new Item(key, value));
        }

   

        //  Easiest approach is to just override toString() method
        //  of the Item class
        jCBCompanyStage = new JComboBox(model);

        // jCBCompanyStage.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));
        HashMap<Integer, String> industry = ES.getIndustry();
        toArray = (String[]) industry.values().toArray(new String[industry.size()]);
        jCBIndustry.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));

        HashMap<Integer, String> channel = ES.getChannel();
        toArray = (String[]) channel.values().toArray(new String[channel.size()]);
        jCBChannel.setModel(new javax.swing.DefaultComboBoxModel<>(toArray));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFCustomerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCBIndustry = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jCBCompanyStage = new javax.swing.JComboBox<>();
        jCBChannel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jBSave = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTFCustomerName.setText("Mandantenname");

        jLabel1.setText("Welcher Branche gehört der Mandant an");

        jLabel2.setText("In welcher Unternehmensphasen befindet sich der Mandant");

        jLabel3.setText("Über welchen Kanal wurde das Mandats-Unternehmen gewonnen?");

        jBSave.setText("Speichern");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Intern");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBSave)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(203, 203, 203))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCBIndustry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBCompanyStage, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCBChannel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFCustomerName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBIndustry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBCompanyStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBChannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jBSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        String S = jTFCustomerName.getText();
        Customer c = new Customer(S);
        // public Customer(String customername, int industryNumber, int companyStageNumber, int Channel, boolean internal) {
        String chanel = jCBChannel.getSelectedItem().toString();
        String companyStage = jCBCompanyStage.getSelectedItem().toString();
        EnumServices ES = new EnumServices();
        HashMap<Integer, String> HMcompanyStage = ES.getCompanyStage();

        String industry = jCBIndustry.getSelectedItem().toString();

        CustomerService CTS = new CustomerService();
        TreeMap<String, Customer> allCustomers = CTS.getAllCustomers();
        Customer get = allCustomers.get(S);
        int bevor = allCustomers.size();
        if (get == null) {
            Customer ct = new Customer(S);
            allCustomers.put(ct.getCustomername(), ct);
            int saveCustomer = CTS.saveCustomer(ct);
            ct.setId(saveCustomer);
        } else {
            JOptionPane.showMessageDialog(null, "Mandant schon vorhanden!");
        }
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSave;
    private javax.swing.JComboBox<String> jCBChannel;
    private javax.swing.JComboBox<String> jCBCompanyStage;
    private javax.swing.JComboBox<String> jCBIndustry;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTFCustomerName;
    // End of variables declaration//GEN-END:variables
}
